# config.toml

[Program]
VERSION = "1.0.0"
REDPACKET_FILEID = "your_redpacket_fileid_here"

[Config]
LOGGING = true
LOG_LEVEL = 30
SQLALCHEMY_LOG = true
PROXY = "http://your_proxy_here:port"
MAX_RETRY = 5
DATABASES_DIR = "path_to_your_databases_dir"
SALT = "your_salt_here"
BANGUMI_TOKEN = "your_bangumi_token_here"

[Bot]
ADMIN = [0]
BOT_TOKEN = "your_bot_token_here"
BASE_URL = "https://api.telegram.org/bot"
TIMEOUT = 20
REDPACKET_IMG = "path_to_your_redpacket_img"
USER_GEN_CDK = true
USER_GEN_CDK_POINT = 300
CHECKIN_POINT_MAX = 20
CHECKIN_POINT_MIN = 2
GROUP_CHAT_ID = "your_group_chat_id_here"
CHANNEL_CHAT_ID = "your_channel_chat_id_here"
MUST_JOIN_CHANNEL = true
MUST_JOIN_GROUP = true
UNLIMITED_REGISTER = false
REGISTER_POINT = 500
EMBY_USERS_SYNC_INTERVAL = 15
LIMIT_USER_COUNT = 3000
LIMIT_USER_COUNT_ENABLED = true
NEW_USER_NOTICE_CHAT_ID = 123456789
NEW_USER_NOTICE_THREAD_ID = 987654321
NEW_USER_NOTICE_STATUS = true
NEW_USER_NOTICE_LINK = true

[Emby]
BASE_URL = "your_emby_base_url_here"
API_KEY = "your_emby_api_key_here"
ADDRESS = '["address1", "address2"]'
