version: '3'

services:
  telegram-jellyfin-bot:
    build:
      context: .
    volumes:
      - ./database:/app/database
      - ./config.toml:/app/config.toml
    container_name: Telegram-Jellyfin-Bot
    network_mode: host
    restart: always
